// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/:userId": {
    params: {
      "userId": string;
    };
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/settings" | "/:userId" | "/login" | "/register";
  };
  "./routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "./routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "./routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/" | "/settings" | "/:userId";
  };
  "./routes/dashboard._index.tsx": {
    id: "routes/dashboard._index";
    page: "/";
  };
  "./routes/dashboard.settings.tsx": {
    id: "routes/dashboard.settings";
    page: "/settings";
  };
  "./routes/dashboard.$userId.tsx": {
    id: "routes/dashboard.$userId";
    page: "/:userId";
  };
  "./routes/_auth.tsx": {
    id: "routes/_auth";
    page: "/login" | "/register";
  };
  "./routes/_auth/login.tsx": {
    id: "routes/_auth/login";
    page: "/login";
  };
  "./routes/_auth/register.tsx": {
    id: "routes/_auth/register";
    page: "/register";
  };
};